@startuml

interface Popup {
  + void show()
  + void close()
}

Popup <|-- Dialog

class Dialog {
  - headerContainer : FlowPanel
  - bodyContainer : FlowPanel
  - buttonContainer : FlowPanel

  + final void show()
  + final void hide()

  # getCssResource() : CssResource
  # createHeader() : Widget
  # createBody() : Widget
  # createButtons() : Widget

  - initCssResource()
}

Dialog -- DialogBoxMitKeyHandler : dialogBox

class DialogBoxMitKeyHandler << gwt >>
class DialogBoxMitKeyHandler {
  .. beispielhafte Setter ..
  + setAnimationEnabled(boolean enable)
  + setAutoHideEnabled(boolean enable)
}

Dialog <|-- StandardDialog

interface ActionHandler {
  + doAction()
}

ActionHandler "many" -- "1" StandardDialog : > registeredCloseHandler

class StandardDialog {
  + setUeberschrift(String Ueberschrift)
  + setImage(ImageType image)
  + setNachrichten(String... nachrichten)
  + addButton() : Button
  + addSchließenHandler(ActionHandler handler)
}

IrgendeinDialogPresenter -- StandardDialog : view

class IrgendeinDialogPresenter {
  - model : Object

  + setModel()
  + afterInjection()
  .. einige init methoden ..
  - initView()
  - initSchlieszenButton()
  - initBestaetigenButton()
}

note top of IrgendeinDialogPresenter
  initView() {
    ...
    view.setUeberschrift("Dialog");
    view.setImage(ImageType.HINWEIS);
    view.setNachricht(...);
    initBestaetigenButton(view.addButton());
    initSchlieszenButton(view.addButton());

    <i>Interaktion</i> <b>view.show()</b>

end note

@enduml