@startuml

interface Popup {
  + void show()
  + void close()
}

Popup <|-- Dialog

class Dialog {
  - headerContainer : FlowPanel
  - bodyContainer : FlowPanel
  - buttonContainer : FlowPanel

  + final void show()
  + final void hide()

  # getCssResource() : CssResource
  # createHeader() : Widget
  # createBody() : Widget
  # createButtons() : Widget

  - initCssResource()
}

Dialog *-- GwtPopupDialog : popupDialog

class GwtPopupDialog {
  # getContentPanel() : Panel
}



Dialog <|-- StandardDialog

interface ActionHandler {
  + doAction()
}

ActionHandler "many" -- "1" StandardDialog : > registeredCloseHandler

class StandardDialog {
  + setUeberschrift(String Ueberschrift)
  + setImage(ImageType image)
  + setNachrichten(String... nachrichten)
  + addButton() : Button
  + addSchließenHandler(ActionHandler handler)
}

IrgendeinDialogPresenter -- StandardDialog : view

class IrgendeinDialogPresenter {
  - model : Object
  - initView()
}

note top of IrgendeinDialogPresenter
  initView() {
    ...
    view.setUeberschrift("Dialog");
    view.setImage(ImageType.HINWEIS);
    view.setNachricht(...);
    initBestaetigenButton(view.addButton());
    initSchlieszenButton(view.addButton());

end note

@enduml